/*
;    Project:       Open Vehicle Monitor System
;    Date:          22th March 2026
;
;    Changes:
;    1.0  Initial release
;
;    (C) 2026       Carsten Schmiemann
;
; Permission is hereby granted, free of charge, to any person obtaining a copy
; of this software and associated documentation files (the "Software"), to deal
; in the Software without restriction, including without limitation the rights
; to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
; copies of the Software, and to permit persons to whom the Software is
; furnished to do so, subject to the following conditions:
;
; The above copyright notice and this permission notice shall be included in
; all copies or substantial portions of the Software.
;
; THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
; IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
; FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
; AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
; LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
; OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
; THE SOFTWARE.
*/

#include "ovms_webserver.h"

/**
 * HandleMetrics: display all metrics with live updates
 */
void OvmsWebServer::HandleMetrics(PageEntry_t& p, PageContext_t& c)
{
  c.head(200);
  PAGE_HOOK("body.pre");

  c.print(
    "<style>\n"
      "#metrics-table { font-size: 13px; }\n"
      "#metrics-table td { font-family: \"Menlo\", \"Consolas\", \"Liberation Mono\", monospace; }\n"
      "#metrics-table .value-cell { word-break: break-all; }\n"
      "#metrics-table .value-cell.editable { cursor: pointer; }\n"
      "#metrics-table .value-cell.editable[contenteditable=\"true\"] { outline: 2px solid #5cb85c; background-color: #f9fff9; }\n"
      "#metrics-table .value-cell.editing select { border: 1px solid #5cb85c; padding: 2px; }\n"
      "#metrics-table .value-cell.error { color: #d9534f; font-weight: bold; }\n"
      "#metrics-table .value-cell.updated { background-color: rgba(0, 212, 255, 0.25); transition: background-color 0s; }\n"
      ".night #metrics-table .value-cell.updated { background-color: rgba(0, 212, 255, 0.25); }\n"
      "#metrics-table .value-cell.flash { background-color: transparent; transition: background-color 0.8s ease-out; }\n"
      ".filter-buttons { margin-bottom: 10px; }\n"
      ".filter-buttons .btn { margin-right: 5px; margin-bottom: 5px; }\n"
      ".filter-buttons .btn.active { font-weight: bold; }\n"
      ".dataTables_filter { margin-bottom: 10px; }\n"
    "</style>\n"
    "<div class=\"panel panel-primary panel-single receiver\" id=\"metrics-panel\">\n"
      "<div class=\"panel-heading\">Metrics</div>\n"
      "<div class=\"panel-body\">\n"
        "<div class=\"filter-buttons\">\n"
          "<button type=\"button\" class=\"btn btn-default active\" data-filter=\"\">All</button>\n"
          "<button type=\"button\" class=\"btn btn-default\" data-filter=\"^v\\.\">Vehicle (v.)</button>\n"
          "<button type=\"button\" class=\"btn btn-default\" data-filter=\"^m\\.\">Module (m.)</button>\n"
          "<button type=\"button\" class=\"btn btn-default\" data-filter=\"^s\\.\">Server (s.)</button>\n"
          "<button type=\"button\" class=\"btn btn-default\" data-filter=\"^x\">Custom (x)</button>\n"
        "</div>\n"
        "<table id=\"metrics-table\" class=\"table table-striped table-bordered table-condensed\">\n"
          "<thead>\n"
            "<tr>\n"
              "<th>Metric</th>\n"
              "<th>Value</th>\n"
              "<th>Unit</th>\n"
            "</tr>\n"
          "</thead>\n"
          "<tbody>\n"
          "</tbody>\n"
        "</table>\n"
      "</div>\n"
    "</div>\n"
    "<script>\n"
    "(function(){\n"
      "var metricsTable;\n"
      "var currentFilter = '';\n"
      "function formatValue(val) {\n"
        "if (val === null || val === undefined) return '';\n"
        "if (Array.isArray(val)) {\n"
          "if (val.length === 0) return '[]';\n"
          "if (val.length <= 10) return '[' + val.join(', ') + ']';\n"
          "return '[' + val.slice(0, 10).join(', ') + ', ... (' + val.length + ' items)]';\n"
        "}\n"
        "if (typeof val === 'object') return JSON.stringify(val);\n"
        "return String(val);\n"
      "}\n"
      "function buildTable() {\n"
        "var rows = [];\n"
        "var names = Object.keys(metrics).sort();\n"
        "for (var i = 0; i < names.length; i++) {\n"
          "var name = names[i];\n"
          "var val = metrics[name];\n"
          "var unit = metrics_label[name] || '';\n"
          "rows.push([name, formatValue(val), unit]);\n"
        "}\n"
        "return rows;\n"
      "}\n"
      "function initTable() {\n"
        "var data = buildTable();\n"
        "metricsTable = $('#metrics-table').DataTable({\n"
          "data: data,\n"
          "columns: [\n"
            "{ title: 'Metric', width: '35%' },\n"
            "{ title: 'Value', width: '50%', className: 'value-cell' },\n"
            "{ title: 'Unit', width: '15%' }\n"
          "],\n"
          "columnDefs: [\n"
            "{\n"
              "targets: 1,\n"
              "createdCell: function(td, cellData, rowData) {\n"
                "$(td).addClass('editable');\n"
              "}\n"
            "}\n"
          "],\n"
          "order: [[0, 'asc']],\n"
          "paging: false,\n"
          "info: false,\n"
          "searching: true,\n"
          "autoWidth: false,\n"
          "responsive: true,\n"
          "language: {\n"
            "search: 'Search:',\n"
            "zeroRecords: 'No matching metrics found'\n"
          "}\n"
        "});\n"
        "$('#metrics-table').data('dataTable', metricsTable).addClass('has-dataTable');\n"
        "bindEditableCells();\n"
      "}\n"
      "function isBooleanValue(val) {\n"
        "if (val === null || val === undefined) return false;\n"
        "var str = String(val).toLowerCase().trim();\n"
        "return (str === 'true' || str === 'false' || typeof val === 'boolean');\n"
      "}\n"
      "function isWritableMetric(name) {\n"
        "if (!metrics || !metrics.hasOwnProperty(name)) return false;\n"
        "var val = metrics[name];\n"
        "if (val === null || val === undefined) return false;\n"
        "if (Array.isArray(val) || typeof val === 'object') return false;\n"
        "return true;\n"
      "}\n"
      "function setMetricValue(metric, value, $cell) {\n"
        "if (!metric) return;\n"
        "var textValue = String(value).trim();\n"
        "if (textValue.length === 0) {\n"
          "$cell.addClass('error');\n"
          "return;\n"
        "}\n"
        "$.ajax({\n"
          "type: 'POST',\n"
          "url: '/api/execute',\n"
          "data: { command: 'metrics set ' + metric + ' ' + textValue },\n"
          "timeout: 10000,\n"
          "success: function(response) {\n"
            "if (response && response.indexOf('Metric set') >= 0) {\n"
              "var parsedValue = Number(textValue);\n"
              "metrics[metric] = isNaN(parsedValue) ? textValue : parsedValue;\n"
              "$('.receiver').trigger('msg:metrics', (function(m){ var o={}; o[m]=metrics[m]; return o; })(metric));\n"
              "$cell.addClass('updated');\n"
              "setTimeout(function(){ $cell.removeClass('updated'); }, 500);\n"
            "} else {\n"
              "$cell.addClass('error');\n"
              "console.warn('metrics set failed:', response);\n"
            "}\n"
          "},\n"
          "error: function(xhr, status, error) {\n"
            "$cell.addClass('error');\n"
            "console.warn('metrics set error', status, error);\n"
          "},\n"
          "complete: function() {\n"
            "$cell.attr('contenteditable', 'false').removeClass('editing');\n"
          "}\n"
        "});\n"
      "}\n"
      "function createBooleanDropdown(metric, currentValue, $cell) {\n"
        "var isBool = isBooleanValue(currentValue);\n"
        "if (!isBool) return false;\n"
        "var currBool = String(currentValue).toLowerCase().trim() === 'true';\n"
        "var origDisplay = $cell.text();\n"
        "$cell.data('orig-value', origDisplay);\n"
        "var $select = $('<select class=\"metric-bool-select\" style=\"padding:2px;font-family:monospace;\">').append($('<option value=\"true\">true</option>').prop('selected', currBool)).append($('<option value=\"false\">false</option>').prop('selected', !currBool));\n"
        "$cell.attr('contenteditable', 'false').html('').append($select).addClass('editing');\n"
        "var handleBoolChange = function() {\n"
          "var newVal = $select.val();\n"
          "$select.disabled = true;\n"
          "$select.off('change blur');\n"
          "if (newVal !== origDisplay) {\n"
            "$cell.text('...');\n"
            "setMetricValue(metric, newVal, $cell);\n"
          "} else {\n"
            "finishEditing($cell);\n"
          "}\n"
        "};\n"
        "var finishEditing = function(el) {\n"
          "el.text(el.data('orig-value')).removeClass('editing').removeData('orig-value');\n"
        "};\n"
        "$select.on('change', handleBoolChange).on('blur', function() { finishEditing($cell); }).focus();\n"
        "return true;\n"
      "}\n"
      "function bindEditableCells() {\n"
        "$('#metrics-table tbody').on('dblclick', 'td.value-cell', function() {\n"
          "var $cell = $(this);\n"
          "if ($cell.find('select').length > 0) return;\n"
          "var rowData = metricsTable.row($cell.closest('tr')).data();\n"
          "if (!rowData || rowData.length < 1) return;\n"
          "var metric = rowData[0];\n"
          "var cellText = $.trim($cell.text());\n"
          "if (createBooleanDropdown(metric, cellText, $cell)) {\n"
            "return;\n"
          "}\n"
          "if ($cell.attr('contenteditable') !== 'true') {\n"
            "$cell.attr('contenteditable', 'true').addClass('editing');\n"
            "$cell.data('orig-value', cellText);\n"
            "$cell.focus();\n"
            "document.execCommand('selectAll', false, null);\n"
          "}\n"
        "});\n"
        "$('#metrics-table tbody').on('keydown', 'td.value-cell.editing', function(ev) {\n"
          "if (ev.key === 'Enter') {\n"
            "ev.preventDefault();\n"
            "$(this).blur();\n"
          "}\n"
          "if (ev.key === 'Escape') {\n"
            "var $cell = $(this);\n"
            "$cell.text($cell.data('orig-value') || '');\n"
            "$cell.attr('contenteditable', 'false').removeClass('editing');\n"
          "}\n"
        "});\n"
        "$('#metrics-table tbody').on('blur', 'td.value-cell.editing', function() {\n"
          "var $cell = $(this);\n"
          "var newValue = $.trim($cell.text());\n"
          "var origValue = $cell.data('orig-value');\n"
          "var rowData = metricsTable.row($cell.closest('tr')).data();\n"
          "if (!rowData || rowData.length < 1) return;\n"
          "var metric = rowData[0];\n"
          "if (newValue === origValue) {\n"
            "$cell.attr('contenteditable', 'false').removeClass('editing');\n"
            "return;\n"
          "}\n"
          "setMetricValue(metric, newValue, $cell);\n"
        "});\n"
      "}\n"
      "function updateMetrics(update) {\n"
        "if (!metricsTable) return;\n"
        "var updatedRows = [];\n"
        "metricsTable.rows().every(function(rowIdx) {\n"
          "var data = this.data();\n"
          "var name = data[0];\n"
          "if (update[name] !== undefined) {\n"
            "var newVal = formatValue(metrics[name]);\n"
            "var newUnit = metrics_label[name] || '';\n"
            "if (data[1] !== newVal || data[2] !== newUnit) {\n"
              "data[1] = newVal;\n"
              "data[2] = newUnit;\n"
              "this.data(data);\n"
              "updatedRows.push(rowIdx);\n"
            "}\n"
          "}\n"
        "});\n"
        "// Check for new metrics\n"
        "var existingNames = {};\n"
        "metricsTable.rows().every(function() {\n"
          "existingNames[this.data()[0]] = true;\n"
        "});\n"
        "var newRows = [];\n"
        "for (var name in update) {\n"
          "if (!existingNames[name]) {\n"
            "var val = metrics[name];\n"
            "var unit = metrics_label[name] || '';\n"
            "newRows.push([name, formatValue(val), unit]);\n"
          "}\n"
        "}\n"
        "if (newRows.length > 0) {\n"
          "metricsTable.rows.add(newRows).draw(false);\n"
        "}\n"
        "// Flash updated rows\n"
        "if (updatedRows.length > 0) {\n"
          "metricsTable.rows(updatedRows).nodes().to$().find('.value-cell')\n"
            ".addClass('updated')\n"
            ".each(function() {\n"
              "var el = this;\n"
              "setTimeout(function() {\n"
                "$(el).addClass('flash').removeClass('updated');\n"
                "setTimeout(function() { $(el).removeClass('flash'); }, 500);\n"
              "}, 50);\n"
            "});\n"
        "}\n"
      "}\n"
      "function applyFilter(filter) {\n"
        "currentFilter = filter;\n"
        "if (metricsTable) {\n"
          "metricsTable.column(0).search(filter, true, false).draw();\n"
        "}\n"
      "}\n"
      "// Filter button handling\n"
      "$('.filter-buttons .btn').on('click', function() {\n"
        "var filter = $(this).data('filter');\n"
        "$('.filter-buttons .btn').removeClass('active');\n"
        "$(this).addClass('active');\n"
        "applyFilter(filter);\n"
      "});\n"
      "// Handle metrics updates\n"
      "$('#metrics-panel').on('msg:metrics', function(e, update) {\n"
        "updateMetrics(update);\n"
      "});\n"
      "// Initialize table\n"
      "if (window.DataTable) {\n"
        "initTable();\n"
      "} else {\n"
        "$.ajax({\n"
          "url: \"" URL_ASSETS_TABLES_JS "\",\n"
          "dataType: \"script\",\n"
          "cache: true,\n"
          "success: function() { initTable(); }\n"
        "});\n"
      "}\n"
    "})();\n"
    "</script>\n");

  PAGE_HOOK("body.post");
  c.done();
}
